service: autocomplete-api
frameworkVersion: '2'

custom:
  cityTableName: CityTable

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: '20201221'
  iam:
    role:
      statements:
        - Effect: 'Allow'
          Action: 'dynamodb:Query'
          Resource: arn:aws:dynamodb:${aws:region}:${aws:accountId}:table/${self:custom.cityTableName}

functions:
  getAutocomplete:
    handler: handler.autocomplete
    environment:
      CITY_TABLE_NAME: ${self:custom.cityTableName}
    events:
      - httpApi:
          path: /autocomplete
          method: get

plugins:
  - serverless-offline
