service: autocomplete-data-producer
frameworkVersion: '2'

custom:
  dataQueueName: autocomplete-city-data-queue
  cityDataBucketName: serverless-course-city-data-bucket

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: '20201221'
  iam:
    role:
      statements:
        - Effect: 'Allow'
          Action: 'sqs:SendMessage'
          Resource: arn:aws:sqs:${aws:region}:${aws:accountId}:${self:custom.dataQueueName}
        - Effect: 'Allow'
          Action:
            - 's3:GetObject'
            - 's3:GetObjectAcl'
            - 's3:ListBucket'
          Resource:
            - arn:aws:s3:::${self:custom.cityDataBucketName}
            - arn:aws:s3:::${self:custom.cityDataBucketName}/*
  s3:
    cityDataBucket:
      name: ${self:custom.cityDataBucketName}

functions:
  producer:
    handler: handler.producer
    timeout: 60
    events:
      - s3: cityDataBucket
    environment:
      QUEUE_URL: https://sqs.us-east-1.amazonaws.com/${aws:accountId}/${self:custom.dataQueueName}
